'use client'
import type { ReactNode } from 'react'
import { useState } from 'react'
import { ArrowLeft, ArrowRight, CalendarDays, Check, Clock3, FileText, HelpCircle, LockKeyhole, MonitorCheck, Search, ShieldCheck, TriangleAlert } from 'lucide-react'
import { Button } from '@/components/ui/button'
import type { Appointment, DemoProps, Reference, Screen, Slot } from '@/lib/types'
import { prettyDate } from '@/lib/types'
import { getReference, getSlots, exportMetrics, metrics } from '@/lib/registro-simulado'

const Shell = ({ children, onHelp, back, title, eyebrow }: { children: React.ReactNode; onHelp: () => void; back?: () => void; title: string; eyebrow: string }) => <div className="kiosk-shell"><header className="kiosk-header"><div className="brand-mark"><span>+</span><div><strong>Salud Norte</strong><small>Turnos digitales</small></div></div><div className="header-status"><span className="status-dot" /> Sistema operativo</div></header><main className="kiosk-main">{back && <button className="back-link" onClick={back}><ArrowLeft data-icon="inline-start" /> Volver</button>}<p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children}</main><button className="help-button" onClick={onHelp}><HelpCircle data-icon="inline-start" /> Necesito ayuda</button></div>
const Panel = ({ children, className = '' }: { children: React.ReactNode; className?: string }) => <section className={`panel ${className}`}>{children}</section>

export function Inicio({ onNavigate, onHelp }: DemoProps) { return <Shell onHelp={onHelp} eyebrow="Recepción autónoma" title="Gestioná tu turno de forma simple"><p className="lead">Retirá un turno para hoy o elegí una fecha próxima. No necesitás crear una cuenta.</p><div className="home-grid"><Panel><CalendarDays className="feature-icon" /><strong>Turnos de hoy</strong><span className="big-number">12</span><small>Disponibles en 4 especialidades</small></Panel><Panel><Clock3 className="feature-icon" /><strong>Última actualización</strong><span className="update-time">09:42</span><small>Información actualizada hace 2 minutos</small></Panel></div><div className="action-row"><Button size="lg" onClick={() => onNavigate('identificacion')}>Comenzar <ArrowRight data-icon="inline-end" /></Button><Button size="lg" variant="outline" onClick={() => onNavigate('seleccion')}>Solo ver cupos</Button></div><div className="privacy-note"><LockKeyhole /> Tu información se consulta de forma segura y no queda guardada en este equipo.</div></Shell> }
export function Identificacion({ onNavigate, onHelp, onBack }: DemoProps & { onBack: () => void }) { const [doc, setDoc] = useState(''); return <Shell onHelp={onHelp} back={onBack} eyebrow="Paso 1 de 3" title="Ingresá tu documento"><p className="lead">Usá solo los números de tu documento. No ingreses puntos ni espacios.</p><Panel><label htmlFor="document">Número de documento</label><input id="document" inputMode="numeric" autoFocus maxLength={8} value={doc} onChange={(e) => setDoc(e.target.value.replace(/\D/g, ''))} onKeyDown={(e) => { if (e.key === 'Enter' && !e.nativeEvent.isComposing && e.keyCode !== 229 && doc.length >= 8) onNavigate('verificacion') }} placeholder="Ej.: 12345678"/><div className="keypad">{['1','2','3','4','5','6','7','8','9','Borrar','0','Aceptar'].map((key) => <button key={key} onClick={() => key === 'Borrar' ? setDoc('') : key === 'Aceptar' ? onNavigate('verificacion') : setDoc((v) => (v + key).slice(0, 8))}>{key}</button>)}</div></Panel><p className="demo-hint">Demo: probá 12345678 (vigente), 87654321 (vencido) o 11112222 (sin referencia).</p></Shell> }
export function Verificacion({ onNavigate, onHelp, onBack, document }: DemoProps & { onBack: () => void; document: string }) { const ref = getReference(document); if (!ref) return <Derivacion onNavigate={onNavigate} onHelp={onHelp} reason="No encontramos una referencia activa asociada a este documento." />; if (ref.status === 'vencida') return <Derivacion onNavigate={onNavigate} onHelp={onHelp} reason="La referencia registrada está vencida. Actualizala en el módulo de atención." />; return <Shell onHelp={onHelp} back={onBack} eyebrow="Paso 2 de 3" title="Referencia verificada"><Panel className="verified"><div className="success-icon"><Check /></div><div><strong>Podés continuar</strong><p>Encontramos una referencia vigente.</p></div></Panel><div className="detail-list"><div><span>Especialidad</span><strong>{ref.specialty}</strong></div><div><span>Origen</span><strong>{ref.origin}</strong></div><div><span>Vigencia</span><strong>{ref.validUntil}</strong></div></div><Button size="lg" onClick={() => onNavigate('seleccion')}>Ver horarios disponibles <ArrowRight data-icon="inline-end" /></Button></Shell> }
export function Seleccion({ onNavigate, onHelp, onBack, document, onSelected }: DemoProps & { onBack: () => void; document: string; onSelected: (slot: Slot) => void }) { const ref = getReference(document); const [selected, setSelected] = useState<Slot | null>(null); const slots = getSlots(ref?.specialty ?? 'Medicina general'); return <Shell onHelp={onHelp} back={onBack} eyebrow="Paso 3 de 3" title="Elegí un horario"><p className="lead">Mostramos primero la fecha más cercana. El turno se reserva al confirmar.</p><div className="slot-list">{slots.map((slot) => <button className={`slot ${selected?.id === slot.id ? 'selected' : ''}`} key={slot.id} onClick={() => setSelected(slot)}><CalendarDays /><span><strong>{prettyDate(slot.date)}</strong><small>{slot.time} · {slot.available} cupos disponibles</small></span>{selected?.id === slot.id && <Check className="slot-check" />}</button>)}</div>{slots.length === 0 && <Panel><TriangleAlert /> No hay cupos próximos para esta especialidad.</Panel>}<Button size="lg" disabled={!selected} onClick={() => { if (selected) { onSelected(selected); onNavigate('confirmacion') } }}>Continuar <ArrowRight data-icon="inline-end" /></Button></Shell> }
export function Confirmacion({ onNavigate, onHelp, onBack, document, selected }: DemoProps & { onBack: () => void; document: string; selected: Slot }) { return <Shell onHelp={onHelp} back={onBack} eyebrow="Revisá antes de confirmar" title="¿Confirmamos tu turno?"><Panel className="appointment-summary"><span>Tu turno</span><strong>{selected.specialty}</strong><div><CalendarDays /> {prettyDate(selected.date)}</div><div><Clock3 /> {selected.time}</div><small>Documento terminado en {document.slice(-4)}</small></Panel><Button size="lg" onClick={() => onNavigate('comprobante')}>Confirmar turno <Check data-icon="inline-end" /></Button><p className="muted-center">Al confirmar, este cupo quedará reservado para vos.</p></Shell> }
export function Comprobante({ onNavigate, onHelp, appointment }: DemoProps & { appointment: Appointment }) { return <Shell onHelp={onHelp} eyebrow="Turno confirmado" title="Listo, tu turno está reservado"><Panel className="ticket"><div className="success-icon"><Check /></div><strong>{appointment.specialty}</strong><h2>{prettyDate(appointment.date)}</h2><p><Clock3 /> {appointment.time}</p><div className="barcode" aria-label={`Código de turno ${appointment.code}`} /> <span className="ticket-code">{appointment.code}</span></Panel><p className="lead small">Guardá este código. Presentalo en recepción al llegar.</p><Button variant="outline" size="lg" onClick={() => onNavigate('inicio')}>Finalizar</Button></Shell> }
export function Derivacion({ onNavigate, onHelp, reason }: DemoProps & { reason: string }) { return <Shell onHelp={onHelp} eyebrow="Necesitamos ayudarte" title="Continuá en el módulo de atención"><Panel className="warning"><TriangleAlert /><div><strong>No pudimos asignar un turno digital</strong><p>{reason}</p></div></Panel><div className="detail-list"><div><span>Turno preferente</span><strong>Solicitá prioridad en recepción</strong></div><div><span>Módulo</span><strong>Atención al paciente · Planta baja</strong></div></div><Button size="lg" onClick={() => onNavigate('inicio')}>Volver al inicio</Button></Shell> }
export function Ingreso() { const [code, setCode] = useState(''); const valid = code.toUpperCase() === 'T-482731'; return <div className="staff-view"><div className="staff-card"><MonitorCheck /><p className="eyebrow">Uso interno</p><h1>Verificación de ingreso</h1><input value={code} onChange={(e) => setCode(e.target.value)} placeholder="Código de turno o documento"/><div className={`lookup-result ${code ? (valid ? 'valid' : 'invalid') : ''}`}>{code && (valid ? <><Check /> Turno válido · Cardiología · 09:30</> : <><TriangleAlert /> No encontramos ese código</>)}</div><Button onClick={() => setCode('')}>Nueva consulta</Button></div></div> }
export function Metricas() { return <div className="staff-view"><div className="metrics-card"><div className="metrics-heading"><div><p className="eyebrow">Panel de operación</p><h1>Métricas de sesión</h1></div><a className="download-link" href={exportMetrics()} download="metricas-kiosco.csv"><FileText /> Exportar CSV</a></div><div className="metric-grid"><div><span>Ingresos</span><strong>{metrics.attempts}</strong></div><div><span>Derivaciones</span><strong>{metrics.derivations}</strong></div><div><span>Abandonos</span><strong>{metrics.abandoned}</strong></div></div><h2>Tiempo promedio por pantalla</h2>{Object.entries(metrics.screenTimes).map(([name, value]) => <div className="bar-row" key={name}><span>{name}</span><div><i style={{ width: `${value}%` }} /></div><strong>{value}s</strong></div>)}</div></div> }
